from win32api import GetSystemMetrics

# Screen Constants
SCREEN_WIDTH = GetSystemMetrics(0) - 400
SCREEN_HEIGHT = GetSystemMetrics(1) - 200

# Color Constants
WHITE = (255, 255, 255)
TRANSPARENT_WHITE = (255, 255, 255, 70)
BLACK = (0, 0, 0)
LIGHT_CYAN_BLUE = (100, 181, 246)
BEIGE = (245, 245, 220)
TRANSPARENT = (0, 0, 0, 0)

# Hexagon Constants
HEXAGON_WIDTH = 115
HEXAGON_HEIGHT = 115
HEXAGON_X_CENTER = HEXAGON_WIDTH / 2
HEXAGON_Y_CENTER = HEXAGON_HEIGHT / 2
HEXAGON_SIDE = HEXAGON_WIDTH / 2
HEXAGON_CENTER = HEXAGON_HEIGHT / 2
HEXAGON_X_AXIS = SCREEN_WIDTH / 2 - HEXAGON_WIDTH / 2 - HEXAGON_WIDTH
HEXAGON_Y_AXIS = 75

# Sprite Constants
HEX_SPRITE_WOOD = "../Assets/wood.jpg"

# Dice Constants
DICE_WIDTH = 80
DICE_HEIGHT = 80
DICE_X_AXIS = SCREEN_WIDTH - DICE_WIDTH * 2 - 20
DICE_Y_AXIS = SCREEN_HEIGHT - DICE_HEIGHT - 50 - 10
DICE_CORNER_RADIUS = 10
DOT_RADIUS = 7
DOT_OFFSET_UP = DICE_WIDTH / 4
DOT_OFFSET_CENTER = DICE_WIDTH / 2
DOT_OFFSET_DOWN = DICE_WIDTH - DOT_OFFSET_UP
DICE_BTN_WIDTH = 200
DICE_BTN_HEIGHT = 50
DICE_BTN_X_AXIS = SCREEN_WIDTH - DICE_BTN_WIDTH - 5
DICE_BTN_Y_AXIS = SCREEN_HEIGHT - 50 - 5

# Menu Constants
FONT_PATH = "../Assets/Fonts/Grand9K Pixel.ttf"
BACKGROUND_PATH = "../Assets/Catan_1920x1080.jpg"
MUSIC_PATH = "../Assets/Music/Cunja Mija by Vox Vulgaris Crop.mp3"
TITLE_TEXT = "Catan"
TITLE_X_AXIS = SCREEN_WIDTH / 2
TITLE_Y_AXIS = 100
SHORT_DESCRIPTION_TEXT = "A game of wonders..."

## Play Button
PLAY_TEXT = "Play"
PLAY_BTN_WIDTH = 200
PLAY_BTN_HEIGHT = 100
PLAY_BTN_X_AXIS = SCREEN_WIDTH - PLAY_BTN_WIDTH - 50
PLAY_BTN_Y_AXIS = SCREEN_HEIGHT - PLAY_BTN_HEIGHT - 300
PLAY_SIZE = 50

## Options Button
OPTIONS_TEXT = "Options"
OPTIONS_BTN_WIDTH = 250
OPTIONS_BTN_HEIGHT = 100
OPTIONS_BTN_X_AXIS = SCREEN_WIDTH - OPTIONS_BTN_WIDTH - 50
OPTIONS_BTN_Y_AXIS = SCREEN_HEIGHT - OPTIONS_BTN_HEIGHT - 150
OPTIONS_SIZE = 50

## Quit Button
QUIT_TEXT = "Quit"
QUIT_BTN_WIDTH = 200
QUIT_BTN_HEIGHT = 100
QUIT_BTN_X_AXIS = SCREEN_WIDTH - QUIT_BTN_WIDTH - 50
QUIT_BTN_Y_AXIS = SCREEN_HEIGHT - QUIT_BTN_HEIGHT
QUIT_SIZE = 50

## Back Button
BACK_TEXT = "Back"
BACK_BTN_WIDTH = 200
BACK_BTN_HEIGHT = 100
BACK_BTN_X_AXIS = 50
BACK_BTN_Y_AXIS = SCREEN_HEIGHT - BACK_BTN_HEIGHT
BACK_SIZE = 50
